networks:
  default:
    external: true
    name: ks201

services:

  producer:
    image: ks201_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-clients.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./producer-1.0.tar:/app.tar
      - ./jmx-exporter-config.yml:/jmx-exporter-config.yml
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      TOPIC: bag-check
      PAUSE: 1

  producer-expedite:
    image: ks201_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-clients.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./producer-1.0.tar:/app.tar
      - ./jmx-exporter-config.yml:/jmx-exporter-config.yml
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      TOPIC: bag-check-expedite
      PAUSE: 100

  streams-baggage:
    image: ks201_app:latest
    stop_grace_period: 120s
    healthcheck:
      test: /healthcheck-streams.sh || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
    volumes:
      - ./streams-baggage-1.0.tar:/app.tar
      - ./jmx-exporter-config.yml:/jmx-exporter-config.yml
    environment:
      BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      STREAMS_NUM_STREAM_THREADS: 2
#      STREAMS_STATE_DIR: /STATE_STORE_DIRECTORY
      INPUT_PATTERN: "bag-check.*"
      OUTPUT: 'output-bag-check'
