global:
  scrape_interval: 5s

scrape_configs:
  - job_name: zookeeper
    static_configs:
      - targets:
          - zookeeper:7071
        labels:
          cluster_type: "zookeeper"
          cluster_id: "kafka-zookeeper"
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
  - job_name: kafka
    static_configs:
      - targets:
        - controller-0:7071
        - broker-1:7071
        - broker-2:7071
        - broker-3:7071
        - broker-4:7071
        labels:
          cluster_type: "kafka"
          cluster_id: "kafka-core"
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
  - job_name: kafka-streams
    scrape_interval: 2s
    file_sd_configs:
      - files:
          - /etc/prometheus/*.json
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
